version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: query_api
    # Use 'expose' so this port is accessible on the Docker network but not published to the host
    expose:
      - "8000"
    networks:
      - app_network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: streamlit_ui
    expose:
      - "8501"
    depends_on:
      - api
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      # Mount your custom NGINX configuration into the container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - ui
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
